#!/bin/bash

function alert-me {
echo -ne "helo my.domain.tld\r\n"
echo -ne "ehlo my.domain.tld\r\n"
echo -ne "mail from: <me@my.domain.tld>\r\n"
echo -ne "rcpt to: <my10digitverizonphonenumber@vtext.com>\r\n"
echo -ne "data\r\n"
sleep 2 
echo -ne "Content-type: text/html\r\n"
echo -ne "From: <me@my.domain.tld>\r\n"
echo -ne "To: <my10digitverizonphonenumber@vtext.com>\r\n"
echo -ne "Subject: EMERGENCY: THE WORLD ENDED\r\n"
echo -ne "EMERGENCY: THE WORLD ENDED\r\n"
echo -ne "\r\n"
echo -ne ${emailHTMLStr//\\n/$newline}"\r\n"
echo -ne "\012.\012" 
echo -ne "quit"
sleep 5
} 
alert-me | telnet smtp-sl.vtext.com 25

exit 0

